services:
  - type: web
    name: rag-api
    env: python
    buildCommand: |
      sudo apt-get update
      sudo apt-get install -y build-essential gcc g++ python3-dev tesseract-ocr
      pip install --no-cache-dir -r requirements.txt
      python -m spacy download en_core_web_sm
    startCommand: cd ${RENDER_PROJECT_DIR} && gunicorn --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT api:app
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PYTHONPATH
        value: ${RENDER_PROJECT_DIR}
      - key: GOOGLE_API_KEY
        sync: false
      - key: REDIS_HOST
        sync: false
      - key: REDIS_PORT
        sync: false
      - key: REDIS_PASSWORD
        sync: false
    autoDeploy: true

  - type: redis
    name: rag-redis
    ipAllowList:
      - source: 0.0.0.0/0
        description: everywhere
    plan: free
